name: "autoclovertheater"
services:
    act:
#        image: "alex78218/autoclovertheater:latest"
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "act"
        volumes:
            - "./etc:/app/etc"
        restart: "unless-stopped"
        # 特权模式
        privileged: true
        ports:
          - "58000:8233"