name: "autoclovertheater"
services:
    act:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "act"
        volumes:
            - ".:/app"
        restart: "unless-stopped"
        # 特权模式
        privileged: true
        ports:
          - "58000:8233"