name: "autoclovertheater"
services:
    act:
        image: "alex78218/autoclovertheater:latest"
#        build:
#            context: .
#            dockerfile: Dockerfile
        container_name: "act"
        volumes:
            - "./env.yaml:/app/env.yaml"
        restart: "unless-stopped"
        # 特权模式
        privileged: true
        ports:
          - "58000:8233"