name: "autoclovertheater"
services:
    act:
        image: "alex78218/autoclovertheater"
#        build:
#            context: .
#            dockerfile: Dockerfile
        container_name: "act"
        volumes:
            - ".:/app"
        restart: "unless-stopped"
        # 特权模式
        privileged: true
        network_mode: bridge
        ports:
            - "8233:8233"